from setuptools import find_packages, setup

package_name = 'c4'

setup(
    name=package_name,
    version='0.0.0',
    packages=find_packages(exclude=['test']),
    data_files=[
        ('share/ament_index/resource_index/packages',
            ['resource/' + package_name]),
        ('share/' + package_name, ['package.xml']),
    ],
    install_requires=['setuptools'],
    zip_safe=True,
    maintainer='rokey',
    maintainer_email='rokey@todo.todo',
    description='TODO: Package description',
    license='TODO: License declaration',
    tests_require=['pytest'],
    entry_points={
        'console_scripts': [
            'pub_image = c4.2_6_a_image_publisher_modified:main',
            'show_image = c4.2_6_b_image_subscriber_modified:main',
            'pub_data = c4.2_6_c_data_publisher:main',
            'show_data = c4.2_6_d_data_subscriber:main',
            'pub_yolo = c4.2_6_e_yolo_publisher:main',
            'show_yolo = c4.2_6_f_yolo_subscriber:main',
            'capture_image = c4.3_1_a_capture_image:main',
            'cont_capture_image = c4.3_1_b_cont_capture_image:main',
            'obj_detect = c4.3_4_a_yolov8_obj_det:main',
            'obj_detect_thread = c4.3_4_b_yolov8_obj_det_thread:main',
            'obj_detect_track = c4.3_4_c_yolov8_obj_det_track:main',
            'depth_checker = c4.3_5_a_depth_checker:main',
            'depth_to_3d3 = c4.3_5_b_depth_to_3d:main',
            'depth_to_nav_goal3 = c4.3_5_c_depth_to_nav_goal:main',
            'nav_to_person = c4.3_5_d_nav_to_person:main',
            'view_image_select = day2.view_image_select:main',
            'nav_person = c4.3_5_d_nav_to_person:main',
            'nav_person2 = c4.3_5_d_nav_to_person_2:main',
            'nav_to_pose = c4.4_4_a_nav_to_pose:main',
            'nav_to_pose_modified = c4.4_4_a_nav_to_pose_copy:main',
            'nav_through_poses = c4.4_4_b_nav_through_poses:main',
            'follow_waypoints = c4.4_4_c_follow_waypoints:main',
            'create_path = c4.4_4_d_create_path:main',
            'mail_delivery = c4.4_4_e_mail_delivery:main',
            'patrol_loop = c4.4_4_f_patrol_loop:main',
            'depth_to_3d = c4.4_5_b_depth_to_3d:main',
            'depth_to_nav_goal = c4.4_5_c_depth_to_nav_goal:main',
            'depth_to_3d_origin = c4.depth_to_3d_origin:main',
            'depth_to_nav_goal_origin = c4.4_5_c_depth_to_nav_goal_origin:main',
            'msg_to_goal = c4.msg_to_goal:main',
            'robot_control = c4.robot_control:main',
            'yolo_depth = c4.yolo_depth:main',
            'depth_to_3d_modified_1 = c4.4_5_b_depth_to_3d_modified_1:main',
            'depth_to_3d_modified_2 = c4.4_5_b_depth_to_3d_modified_2:main',
            'robot_control1 = c4.robot_control_1:main',
            'robot_control2 = c4.robot_control_2:main',
            'robot_detect = c4.robot_detect:main',
            'robot_detect_0 = c4.robot_detect_0:main',
            'robot_control_4 = c4.robot_control_4:main',
            'robot_detect_1 = c4.4_5_b_depth_to_3d_modified_copy:main',
            'robot_detect_2 = c4.robot_detect_2:main',
            'robot_detect_3 = c4.robot_detect_3:main'
        ],
    },
)
